source 'https://cdn.cocoapods.org'
platform :ios, '17.6'

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios
  pod 'ios', :path => '.'
end
