name: Dekstop
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up latest JDK code tool jextract'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: jextract
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "23"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: native_helper
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew client:packageReleaseDistributionForCurrentOS
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: desktopapp-${{ matrix.os }}
          path: |
            build/compose/binaries/main-release/deb/*.deb
            build/compose/binaries/main-release/pkg/*.pkg
            build/compose/binaries/main-release/rpm/*.rpm
            build/compose/binaries/main-release/msi/*.msi
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Download Artifacts from Ubuntu
        with:
          name: desktopapp-ubuntu-latest
      - uses: actions/download-artifact@v4
        name: Download Artifacts from MacOS
        with:
          name: desktopapp-macos-latest
      - uses: actions/download-artifact@v4
        name: Download Artifacts from Ubuntu (ARM)
        with:
          name: desktopapp-ubuntu-24.04-arm
      - uses: actions/download-artifact@v4
        name: Download Artifacts from Ubuntu (ARM)
        with:
          name: desktopapp-ubuntu-latest
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/desktop/build/compose/binaries/main-release/deb/*.deb
            app/desktop/build/compose/binaries/main-release/pkg/*.pkg
            app/desktop/build/compose/binaries/main-release/rpm/*.rpm
            app/desktop/build/compose/binaries/main-release/msi/*.msi
